name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright dependencies
      run: |
        python -m pip install playwright
        python -m playwright install

    - name: Run Python Script
      run: |
        python main.py 

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit and push generated file
      run: |
        git add difficulty_counts.svg  
        git commit -m "Add generated difficulty_counts.svg" 
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
